apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dyna
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: master
  url: https://github.com/mojaorganizacjatestowa/flux_dyna
